### ISSUE TITLE
Gathering information on real time pose estimation algorithms

### ISSUE THREAD

**Issue by relientm96** [relientm96/capstone2020#10]
## Objectives for this issue:
- We need to further look into algorithms that are suitable to work with in our music gesture recognition system.
- Try to find a good one that can detect upper body parts in real time
- Using rubric to compare

Try to put in your input through this thread

**Comment by relientm96** [comment]
I'm just going to add it here:
https://colab.research.google.com/github/tugstugi/dl-colab-notebooks/blob/master/notebooks/OpenPose.ipynb#scrollTo=nZ3Ud9zLgOoQ

So I found an online jupyter notebook that I can run openpose with, you can put in any youtube ID and the program is able to detect the feature on the video.

You can change the runtime parameters as well, so you can run on hand specific detection with this command:
```
!cd openpose && ./build/examples/openpose/openpose.bin --hand --video ../video.mp4 --write_json ./output/ --display 0  --write_video ../openpose.avi
```

If it is difficult to run open pose on our own PCs, I think we can just try to run it on online google colab or notebooks online that have gpus able to run open pose.

**Comment by Y1Ck** [comment]
https://github.com/tugstugi/dl-colab-notebooks#pose-detection;

a very convenient place to test all the state-of-art (according to the research papers)
pose estimations;
at least, we could judge qualitatively

**Comment by relientm96** [comment]
We are good with OpenPose.
