### ISSUE TITLE
Use Github API to create a Gantt chart

### ISSUE THREAD

**Issue by nivlekp** [relientm96/capstone2020#11]
Try using Github API to create a Gantt chart, or whatever chart that we could include in our report.

**Comment by relientm96** [comment]
I'll look into this soon when I have time. There are a few open source repos that I might try

**Comment by Y1Ck** [comment]
perhaps JSON, or HTML to render?
https://docs.anychart.com/Gantt_Chart/Project_Chart

**Comment by relientm96** [comment]
Hey @nivlekp I've seen from your branch that you were able to get the data out from the repo from curl requests but I found an alternative using google sheets:

Link to the video here:
https://www.youtube.com/watch?v=-crraoSMxc0

**Comment by nivlekp** [comment]
I was thinking of using tikz to draw the chart for better integration into our final report.
However please feel free to go ahead with other methods as well if you found them easier.
Also @relientm96 , from your link, I could not really see how to automate the drawing process by integrating the google sheets with git. Or did I miss something?

**Comment by relientm96** [comment]
@nivlekp  it wasnt automation, its still manual but it generates a visual gantt chart from google sheets. Nothing special haha
