### ISSUE TITLE
[KIV] Creating a block diagram of our system

### ISSUE THREAD

**Issue by relientm96** [relientm96/capstone2020#19]
A simple block diagram with description to help us and Jonathan see the overview of our system.

**Comment by relientm96** [comment]
I was thinking of using draw.io to draw diagrams out

**Comment by relientm96** [comment]
- We can use Miro to create a block diagram of our system

**Comment by nivlekp** [comment]
Sorry I saw the comment about Miro just now.

I just drawn something in draw.io, here is the link.
https://drive.google.com/file/d/1QDMFNl4ht224_sZ5mZoExahwnITvpl3_/view?usp=sharing

I hope this might be sort of a starter of our system.
Please feel free to change things and comment.
