### ISSUE TITLE
[KIV] Creating rubric to identify best pose estimation algorithm

### ISSUE THREAD

**Issue by relientm96** [relientm96/capstone2020#20]
- Creating a document listing out what is traits we need to measure to choose right algorithm

**Comment by relientm96** [comment]
I am happy to do this via word/doc/docx files or google sheets/excel

**Comment by relientm96** [comment]
Anyone here has any good metric to measure each algorithm by?
I can think of:
- Ease of setting up environment and pre-req tools
- Processing latency as a function of frame rate?
- Amount of documentation and tutorials online

**Comment by Y1Ck** [comment]
i think we should not rush on this, as we could always come back to change the mainframe or improve it. But this assumes that we can develop pose estimation and gesture recognition separately;
instead, by the assumption above, we should focus on the pipelining pose estimation with gesture recognition?
for the time being, we should go by jonathan's advice: the easiest to set up and get it run?

**Comment by relientm96** [comment]
@Y1Ck will be in charge of setting up a rubric, since he has done research.
