### ISSUE TITLE
Project Meeting - Week 5 (3rd March 2020)

### ISSUE THREAD

**Issue by relientm96** [relientm96/capstone2020#28]
Use this thread to put in what you think we should discuss on Friday's Meeting.

**Comment by relientm96** [comment]
Agenda So far that I have:

- Update on using UniMelb Research Cloud
- Re-iterating our Project Timeline (Adjusting Timeline)
- Re-assigning tasks

**Comment by nivlekp** [comment]
The zoom link is here: https://unimelb.zoom.us/j/701538996
