### ISSUE TITLE
Focus on Testing out Unimelb Research Cloud

### ISSUE THREAD

**Issue by relientm96** [relientm96/capstone2020#29]
Putting this as our main task now (up to 3rd March meeting), to test out working OpenPose on Unimelb Research Cloud.

**Comment by nivlekp** [comment]
__Update__: Submitted an allocation request for Research Cloud. Now awaiting for it to get processed.

**Comment by relientm96** [comment]
Welp, I guess we can close this? We can't use it !

**Comment by relientm96** [comment]
I am closing this issue, as we do not have access given to us
