### ISSUE TITLE
Project Management Tool System Methodology

### ISSUE THREAD

**Issue by relientm96** [relientm96/capstone2020#3]
Need to finalize a proper method/system to get work flow done in our group.

So far, we have the idea of using branches to apply your changes and create pull requests so that we can all review before merging to the master.

Still need to figure out way of assigning tasks, etc...

**Comment by relientm96** [comment]
I am currently in the midst of experimenting with the GitHub in built issues, and project management system. Will come up with a document listing steps soon.

**Comment by relientm96** [comment]
Okay, I have come up with a way to assign tasks and how to review them.

We have three tabs that we need to be aware of. 
- Issues : Contains all project tasks
- Pull Requests: Contains the pull requests needed to be reviewed before merging to master
- Projects: Our Kanban like project management board

### Issues
The issues tab is where we can look at all the existing tasks that needs to be solved. 
To create a new task:
1. Click on New Issue
2. Write down title and information
3. Assign people in charge of tasks under the "Assignees" tab on the right
4. Assign a label to describe what kind of task under the "Label"
5. Assign our project board to under the "Projects" tab
6. Once done submit the issue, the issue would then be automatically synced with the Kanban projects board.

### Pull Requests
You can view all current pending pull requests here.
1. After creating and pushing your branch, and after you clicking on sending pull requests, all of the requests would be routed here.
2. Click and comment/review each pull request accordingly.
3. Once satisfied, someone can just click on the merge pull request at the end of the thread.

### Projects
This is our Kanban like project dashboard that is helpful to visualize our workflow. It has three columns: To Do, In Progress and Done.
1. All newly created issues from the issues tab and newly created pull requests are all sent here.
2. If work is in progress on issue/pull request, drag them into the In Progress column
3. Once issue has been closed or pull request successfully merged, then all of them would be automatically moved into the Done column.

Hope this was clear enough, let me know on what you think or what else we can do to manage our work! :)

**Comment by nivlekp** [comment]
Thanks @relientm96 for looking into this! I think this is clear and the video that you sent us on Slack really helps explaining it as well. However I think I would have to actually use it first to fully understand how it works.

**Comment by nivlekp** [comment]
Upon looking up project and milestone in Github, I am more inclined to have projects as smaller tasks rather than just "Real-time Pose Estimation". This way we can break down the project into smaller tasks, rather than having just TODOs, in progress, and done in a rather unorganised way. Having said that, the work breakdown structure would only be possible after we have decided the project goal/scope

**Comment by relientm96** [comment]
My bad. I misunderstood milestones before and didn't know what to put as project title. Let me change it to "Project Planning".

**Comment by relientm96** [comment]
Just changed the title and description of the project. Let me know if it is okay or if I got it wrong.

**Comment by relientm96** [comment]
So from what I have read, our project management details should look like

We have our capstone project. It has many projects/epics which are like overall goals throughout our capstone duration

Each project/epic has many milestones, which are like checkpoints to achieving the project/epic. Miestones contain a deadline as well to keep track on due dates 

Each milestone consists of many individual small tasks (issues) which are the actual tasks that we need to achieve in order to complete a milestone.

Hope this makes sense to everyone and if everyone is happy we can try to use this as a framework to organize our project goals and timeline.

I also happy to do it if you guys find it confusing!

**Comment by relientm96** [comment]
Hey all, if we are happy with this method of handling our project tasks, shall I close this issue? Or do you guys have any feedback?

**Comment by Y1Ck** [comment]
thank you Matthew;
 im happy with it;

**Comment by relientm96** [comment]
Sorry just awaiting @nivlekp 's response before I close it.

**Comment by relientm96** [comment]
Alright I am closing this issue for now as I think we are all comfortable with the workflow methodology. Please feel free to notify again if there is an issue and I will re-open.
